# Generated by Django 5.2.4 on 2025-08-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('is_cancelled', models.BooleanField()),
                ('lead_time', models.IntegerField()),
                ('arrival_date_year', models.IntegerField()),
                ('arrival_date_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('arrival_date_week_number', models.IntegerField()),
                ('arrival_date_day_of_month', models.IntegerField()),
                ('stays_in_weekend_nights', models.IntegerField()),
                ('stays_in_week_nights', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('babies', models.IntegerField()),
                ('meal', models.CharField(choices=[('Undefined', 'No Meal Package'), ('SC', 'No Meal Package'), ('BB', 'Bed & Breakfast'), ('HB', 'Half board'), ('FB', 'Full board')], max_length=9)),
                ('country', models.CharField(max_length=5)),
                ('market_segment', models.CharField(choices=[('Online TA', 'Online TA'), ('Offline TA/TO', 'Offline TA/TO'), ('Direct', 'Direct'), ('Groups', 'Groups'), ('Corporate', 'Corporate'), ('Complementary', 'Complementary')], max_length=13)),
                ('distribution_channel', models.CharField(choices=[('Direct', 'Direct'), ('Corporate', 'Corporate'), ('TA/TO', 'TA/TO'), ('Undefined', 'Undefined')], max_length=9)),
                ('is_repeated_guest', models.BooleanField()),
                ('previous_cancellations', models.IntegerField()),
                ('previous_booking_not_canceled', models.IntegerField()),
                ('reserved_room_type', models.CharField(max_length=1)),
                ('assigned_room_type', models.CharField(max_length=1)),
                ('booking_changes', models.IntegerField()),
                ('deposit_type', models.CharField(choices=[('No Deposit', 'No Deposit'), ('Non Refund', 'Non Refund'), ('Refundable', 'Refundable')], max_length=10)),
                ('agent', models.IntegerField(blank=True, null=True)),
                ('company', models.IntegerField(blank=True, null=True)),
                ('days_in_waiting_list', models.IntegerField()),
                ('customer_type', models.CharField(choices=[('Contract', 'Contract'), ('Group', 'Group'), ('Transient', 'Transient'), ('Transient-party', 'Transient-Party')], max_length=15)),
                ('adr', models.FloatField()),
                ('required_card_parking_spaces', models.IntegerField()),
                ('total_of_special_requests', models.IntegerField()),
                ('reservation_status', models.CharField(choices=[('Check-Out', 'Check-Out'), ('Canceled', 'Canceled'), ('No-Show', 'Undefined')], max_length=9)),
                ('reservation_status_date', models.DateField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
